:projectname: xxx
= Project Title

One Paragraph of project description goes here

== Getting Started

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.

=== Prerequisites

What things you need to install the software and how to install them

[source,java]
----
// TODO: give examples
----

=== Installing

A step by step series of examples that tell you how to get a development env running

Say what the step will be

[source,java]
----
// TODO: give examples
----

And repeat

[source,java]
----
// TODO: ... until finished
----

End with an example of getting some data out of the system or using it for a little demo

== Running the tests

Explain how to run the automated tests for this system

=== Break down into end to end tests

Explain what these tests test and why

[source,java]
----
// TODO: give an example
----

=== And coding style tests

Explain what these tests test and why

[source,java]
----
// TODO: give an example
----

== Deployment

Add additional notes about how to deploy this on a live system

== Built With

- https://spring.io/projects/spring-boot[Spring Boot] - The application framework used
- https://gradle.org[Gradle] - Build tool

== Contributing

Please read https://github.com/openmf/{projectname}/CONTRIBUTING.adoc[CONTRIBUTING.adoc] for details on our code of conduct, and the process for submitting pull requests to us.

== Versioning

We use http://semver.org/[SemVer] for versioning. For the versions available, see the https://github.com/your/{projectname}/tags[tags on this repository].

== Authors

- *https://github.com/vidakovic[Aleksandar Vidakovic]* - _Initial work_

See also the list of https://github.com/openmf/{projectname}/CONTRIBUTORS[CONTRIBUTORS] who participated in this project.

== License

This project is licensed under the MPL-2.0 License - see the https://github.com/openmf/{projectname}/LICENSE[LICENSE] file for details

== Acknowledgments

* Hat tip to anyone whose code was used
* Inspiration
* etc
